"""add_redirects_count

Revision ID: 161c73d77128
Revises: 6d470c19afa5
Create Date: 2026-04-30 15:41:44.649261

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "161c73d77128"
down_revision: str | Sequence[str] | None = "6d470c19afa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("short_urls", sa.Column("redirects_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("short_urls", "redirects_count")
    # ### end Alembic commands ###
