"""add created at

Revision ID: 6d470c19afa5
Revises: 95af0dd6e27e
Create Date: 2026-04-29 14:10:59.924360

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d470c19afa5"
down_revision: str | Sequence[str] | None = "95af0dd6e27e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "short_urls",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("short_urls", "created_at")
    # ### end Alembic commands ###
