"""init

Revision ID: 95af0dd6e27e
Revises:
Create Date: 2026-04-29 14:05:27.987380

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95af0dd6e27e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "short_urls",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("long_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("short_urls")
    # ### end Alembic commands ###
